// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AvatarDropdown: typeof import('./src/components/GlobalHeader/AvatarDropdown.vue')['default']
    ChangePassword: typeof import('./src/components/GlobalHeader/ChangePassword.vue')['default']
    Ellipsis: typeof import('./src/components/Ellipsis/Ellipsis.vue')['default']
    FooterToolBar: typeof import('./src/components/FooterToolbar/FooterToolBar.vue')['default']
    FormSearch: typeof import('./src/components/FormSearch/index.vue')['default']
    GlobalFooter: typeof import('./src/components/GlobalFooter/index.vue')['default']
    ImportFileModal: typeof import('./src/components/ImportModal/ImportFileModal.vue')['default']
    RightContent: typeof import('./src/components/GlobalHeader/RightContent.vue')['default']
    UserInfoSetting: typeof import('./src/components/GlobalHeader/UserInfoSetting.vue')['default']
  }
}

export { }
